security:
    encoders:
        App\Domain\Entity\Client:
            algorithm: bcrypt

    providers:
        client_provider:
            entity:
                class: App\Domain\Entity\Client
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
            pattern: ^/api/doc
            security: false

        login_client:
            pattern:  ^/api/login/client
            stateless: true
            anonymous: true
            provider: client_provider
            json_login:
                check_path:               /api/login/client
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        register_client:
            pattern: ^/api/clients$
            stateless: true
            anonymous: true

        api:
            pattern: ^/api
            stateless: true
            provider: client_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login,      roles: IS_AUTHENTICATED_ANONYMOUSLY,    methods: [POST] }
        - { path: ^/api/clients,    roles: IS_AUTHENTICATED_ANONYMOUSLY,    methods: [POST] }
        - { path: ^/api,            roles: IS_AUTHENTICATED_FULLY }
